// ABI for AmmAuctionFacet - Solo auctions with single maker
export const ammAuctionFacetAbi = [
  // Events
  {
    type: 'event',
    name: 'AuctionCreated',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'makerPositionKey', type: 'bytes32', indexed: true },
      { name: 'makerPositionId', type: 'uint256', indexed: true },
      { name: 'poolIdA', type: 'uint256', indexed: false },
      { name: 'poolIdB', type: 'uint256', indexed: false },
      { name: 'tokenA', type: 'address', indexed: false },
      { name: 'tokenB', type: 'address', indexed: false },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
      { name: 'startTime', type: 'uint64', indexed: false },
      { name: 'endTime', type: 'uint64', indexed: false },
      { name: 'feeBps', type: 'uint16', indexed: false },
      { name: 'feeAsset', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionSwapped',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'swapper', type: 'address', indexed: true },
      { name: 'tokenIn', type: 'address', indexed: false },
      { name: 'amountIn', type: 'uint256', indexed: false },
      { name: 'amountOut', type: 'uint256', indexed: false },
      { name: 'feeAmount', type: 'uint256', indexed: false },
      { name: 'recipient', type: 'address', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionFinalized',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'makerPositionKey', type: 'bytes32', indexed: true },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
      { name: 'makerFeeA', type: 'uint256', indexed: false },
      { name: 'makerFeeB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionCancelled',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'makerPositionKey', type: 'bytes32', indexed: true },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
      { name: 'makerFeeA', type: 'uint256', indexed: false },
      { name: 'makerFeeB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionLiquidityAdded',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'makerPositionKey', type: 'bytes32', indexed: true },
      { name: 'amountA', type: 'uint256', indexed: false },
      { name: 'amountB', type: 'uint256', indexed: false },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
    ],
  },
  // Write functions
  {
    type: 'function',
    name: 'createAuction',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'positionId', type: 'uint256' },
          { name: 'poolIdA', type: 'uint256' },
          { name: 'poolIdB', type: 'uint256' },
          { name: 'reserveA', type: 'uint256' },
          { name: 'reserveB', type: 'uint256' },
          { name: 'startTime', type: 'uint64' },
          { name: 'endTime', type: 'uint64' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'feeAsset', type: 'uint8' },
        ],
      },
    ],
    outputs: [{ name: 'auctionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapExactIn',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'minOut', type: 'uint256' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [{ name: 'amountOut', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapExactInOrFinalize',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'minOut', type: 'uint256' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [
      { name: 'amountOut', type: 'uint256' },
      { name: 'finalized', type: 'bool' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'finalizeAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addLiquidity',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'amountA', type: 'uint256' },
      { name: 'amountB', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Read functions
  {
    type: 'function',
    name: 'getAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'makerPositionKey', type: 'bytes32' },
          { name: 'makerPositionId', type: 'uint256' },
          { name: 'poolIdA', type: 'uint256' },
          { name: 'poolIdB', type: 'uint256' },
          { name: 'tokenA', type: 'address' },
          { name: 'tokenB', type: 'address' },
          { name: 'reserveA', type: 'uint256' },
          { name: 'reserveB', type: 'uint256' },
          { name: 'initialReserveA', type: 'uint256' },
          { name: 'initialReserveB', type: 'uint256' },
          { name: 'invariant', type: 'uint256' },
          { name: 'startTime', type: 'uint64' },
          { name: 'endTime', type: 'uint64' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'feeAsset', type: 'uint8' },
          { name: 'makerFeeAAccrued', type: 'uint256' },
          { name: 'makerFeeBAccrued', type: 'uint256' },
          { name: 'treasuryFeeAAccrued', type: 'uint256' },
          { name: 'treasuryFeeBAccrued', type: 'uint256' },
          { name: 'active', type: 'bool' },
          { name: 'finalized', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewSwap',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
    ],
    outputs: [
      { name: 'amountOut', type: 'uint256' },
      { name: 'feeAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionFees',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      { name: 'makerFeeA', type: 'uint256' },
      { name: 'makerFeeB', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
]
