// ABI for CommunityAuctionFacet - Multi-maker pooled auctions
export const communityAuctionFacetAbi = [
  // Events
  {
    type: 'event',
    name: 'CommunityAuctionCreated',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'creatorPositionKey', type: 'bytes32', indexed: true },
      { name: 'creatorPositionId', type: 'uint256', indexed: true },
      { name: 'poolIdA', type: 'uint256', indexed: false },
      { name: 'poolIdB', type: 'uint256', indexed: false },
      { name: 'tokenA', type: 'address', indexed: false },
      { name: 'tokenB', type: 'address', indexed: false },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
      { name: 'startTime', type: 'uint64', indexed: false },
      { name: 'endTime', type: 'uint64', indexed: false },
      { name: 'feeBps', type: 'uint16', indexed: false },
      { name: 'feeAsset', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MakerJoined',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'positionKey', type: 'bytes32', indexed: true },
      { name: 'positionId', type: 'uint256', indexed: false },
      { name: 'amountA', type: 'uint256', indexed: false },
      { name: 'amountB', type: 'uint256', indexed: false },
      { name: 'share', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MakerLeft',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'positionKey', type: 'bytes32', indexed: true },
      { name: 'positionId', type: 'uint256', indexed: false },
      { name: 'withdrawnA', type: 'uint256', indexed: false },
      { name: 'withdrawnB', type: 'uint256', indexed: false },
      { name: 'feesA', type: 'uint256', indexed: false },
      { name: 'feesB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FeesClaimed',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'positionKey', type: 'bytes32', indexed: true },
      { name: 'feesA', type: 'uint256', indexed: false },
      { name: 'feesB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommunityAuctionSwapped',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'swapper', type: 'address', indexed: true },
      { name: 'tokenIn', type: 'address', indexed: false },
      { name: 'amountIn', type: 'uint256', indexed: false },
      { name: 'amountOut', type: 'uint256', indexed: false },
      { name: 'feeAmount', type: 'uint256', indexed: false },
      { name: 'recipient', type: 'address', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommunityAuctionFinalized',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'creatorPositionKey', type: 'bytes32', indexed: true },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommunityAuctionCancelled',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'creatorPositionKey', type: 'bytes32', indexed: true },
      { name: 'reserveA', type: 'uint256', indexed: false },
      { name: 'reserveB', type: 'uint256', indexed: false },
    ],
  },
  // Write functions
  {
    type: 'function',
    name: 'createCommunityAuction',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'positionId', type: 'uint256' },
          { name: 'poolIdA', type: 'uint256' },
          { name: 'poolIdB', type: 'uint256' },
          { name: 'reserveA', type: 'uint256' },
          { name: 'reserveB', type: 'uint256' },
          { name: 'startTime', type: 'uint64' },
          { name: 'endTime', type: 'uint64' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'feeAsset', type: 'uint8' },
        ],
      },
    ],
    outputs: [{ name: 'auctionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'joinCommunityAuction',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'positionId', type: 'uint256' },
      { name: 'amountA', type: 'uint256' },
      { name: 'amountB', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'leaveCommunityAuction',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'positionId', type: 'uint256' },
    ],
    outputs: [
      { name: 'withdrawnA', type: 'uint256' },
      { name: 'withdrawnB', type: 'uint256' },
      { name: 'feesA', type: 'uint256' },
      { name: 'feesB', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimFees',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'positionId', type: 'uint256' },
    ],
    outputs: [
      { name: 'feesA', type: 'uint256' },
      { name: 'feesB', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapExactIn',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'minOut', type: 'uint256' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [{ name: 'amountOut', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'finalizeAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelCommunityAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Read functions
  {
    type: 'function',
    name: 'getCommunityAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creatorPositionKey', type: 'bytes32' },
          { name: 'creatorPositionId', type: 'uint256' },
          { name: 'poolIdA', type: 'uint256' },
          { name: 'poolIdB', type: 'uint256' },
          { name: 'tokenA', type: 'address' },
          { name: 'tokenB', type: 'address' },
          { name: 'reserveA', type: 'uint256' },
          { name: 'reserveB', type: 'uint256' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'feeAsset', type: 'uint8' },
          { name: 'feeIndexA', type: 'uint256' },
          { name: 'feeIndexB', type: 'uint256' },
          { name: 'feeIndexRemainderA', type: 'uint256' },
          { name: 'feeIndexRemainderB', type: 'uint256' },
          { name: 'treasuryFeeAAccrued', type: 'uint256' },
          { name: 'treasuryFeeBAccrued', type: 'uint256' },
          { name: 'indexFeeAAccrued', type: 'uint256' },
          { name: 'indexFeeBAccrued', type: 'uint256' },
          { name: 'activeCreditFeeAAccrued', type: 'uint256' },
          { name: 'activeCreditFeeBAccrued', type: 'uint256' },
          { name: 'totalShares', type: 'uint256' },
          { name: 'makerCount', type: 'uint256' },
          { name: 'startTime', type: 'uint64' },
          { name: 'endTime', type: 'uint64' },
          { name: 'active', type: 'bool' },
          { name: 'finalized', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMakerShare',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'positionKey', type: 'bytes32' },
    ],
    outputs: [
      { name: 'share', type: 'uint256' },
      { name: 'pendingFeesA', type: 'uint256' },
      { name: 'pendingFeesB', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewJoin',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'amountA', type: 'uint256' },
    ],
    outputs: [{ name: 'requiredB', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewCommunitySwap',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
    ],
    outputs: [
      { name: 'amountOut', type: 'uint256' },
      { name: 'feeAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewLeave',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'positionKey', type: 'bytes32' },
    ],
    outputs: [
      { name: 'withdrawA', type: 'uint256' },
      { name: 'withdrawB', type: 'uint256' },
      { name: 'feesA', type: 'uint256' },
      { name: 'feesB', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTotalMakers',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
]
