// ABI for DerivativeViewFacet - Read-only queries for auction discovery and best price routing
export const derivativeViewFacetAbi = [
  {
    type: 'function',
    name: 'getAmmAuction',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'makerPositionKey', type: 'bytes32' },
          { name: 'makerPositionId', type: 'uint256' },
          { name: 'poolIdA', type: 'uint256' },
          { name: 'poolIdB', type: 'uint256' },
          { name: 'tokenA', type: 'address' },
          { name: 'tokenB', type: 'address' },
          { name: 'reserveA', type: 'uint256' },
          { name: 'reserveB', type: 'uint256' },
          { name: 'initialReserveA', type: 'uint256' },
          { name: 'initialReserveB', type: 'uint256' },
          { name: 'invariant', type: 'uint256' },
          { name: 'startTime', type: 'uint64' },
          { name: 'endTime', type: 'uint64' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'feeAsset', type: 'uint8' },
          { name: 'makerFeeAAccrued', type: 'uint256' },
          { name: 'makerFeeBAccrued', type: 'uint256' },
          { name: 'treasuryFeeAAccrued', type: 'uint256' },
          { name: 'treasuryFeeBAccrued', type: 'uint256' },
          { name: 'active', type: 'bool' },
          { name: 'finalized', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionFees',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      { name: 'makerFeeA', type: 'uint256' },
      { name: 'makerFeeB', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionsByPosition',
    inputs: [
      { name: 'positionKey', type: 'bytes32' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionsByPositionId',
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveAuctions',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionsByPool',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionsByToken',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionsByPair',
    inputs: [
      { name: 'tokenA', type: 'address' },
      { name: 'tokenB', type: 'address' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionMeta',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      { name: 'active', type: 'bool' },
      { name: 'expired', type: 'bool' },
      { name: 'startTime', type: 'uint64' },
      { name: 'endTime', type: 'uint64' },
      { name: 'tokenA', type: 'address' },
      { name: 'tokenB', type: 'address' },
      { name: 'reserveA', type: 'uint256' },
      { name: 'reserveB', type: 'uint256' },
      { name: 'priceAInB', type: 'uint256' },
      { name: 'priceBInA', type: 'uint256' },
      { name: 'timeRemaining', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewSwapWithSlippage',
    inputs: [
      { name: 'auctionId', type: 'uint256' },
      { name: 'tokenIn', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'slippageBps', type: 'uint16' },
    ],
    outputs: [
      { name: 'amountOut', type: 'uint256' },
      { name: 'feeAmount', type: 'uint256' },
      { name: 'minOut', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'findBestAuctionExactIn',
    inputs: [
      { name: 'tokenIn', type: 'address' },
      { name: 'tokenOut', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'bestAuctionId', type: 'uint256' },
      { name: 'bestAmountOut', type: 'uint256' },
      { name: 'checked', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOptionSeries',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'writerPositionKey', type: 'bytes32' },
          { name: 'writerPositionId', type: 'uint256' },
          { name: 'poolId', type: 'uint256' },
          { name: 'underlying', type: 'address' },
          { name: 'strikePrice', type: 'uint256' },
          { name: 'expiry', type: 'uint64' },
          { name: 'isCall', type: 'bool' },
          { name: 'collateralLocked', type: 'uint256' },
          { name: 'remaining', type: 'uint256' },
          { name: 'exercised', type: 'bool' },
          { name: 'settled', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOptionSeriesByPositionId',
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFuturesSeries',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'writerPositionKey', type: 'bytes32' },
          { name: 'writerPositionId', type: 'uint256' },
          { name: 'poolId', type: 'uint256' },
          { name: 'underlying', type: 'address' },
          { name: 'deliveryPrice', type: 'uint256' },
          { name: 'expiry', type: 'uint64' },
          { name: 'graceUnlockTime', type: 'uint64' },
          { name: 'underlyingLocked', type: 'uint256' },
          { name: 'remaining', type: 'uint256' },
          { name: 'settled', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFuturesSeriesByPositionId',
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
]
