export const equalIndexFacetV3Abi = [
  {
    type: 'event',
    name: 'IndexCreated',
    inputs: [
      { name: 'indexId', type: 'uint256', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'assets', type: 'address[]', indexed: false },
      { name: 'bundleAmounts', type: 'uint256[]', indexed: false },
      { name: 'flashFeeBps', type: 'uint16', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'createIndex',
    inputs: [
      {
        name: 'p',
        type: 'tuple',
        internalType: 'struct EqualIndexBaseV3.CreateIndexParams',
        components: [
          { name: 'name', type: 'string', internalType: 'string' },
          { name: 'symbol', type: 'string', internalType: 'string' },
          { name: 'assets', type: 'address[]', internalType: 'address[]' },
          { name: 'bundleAmounts', type: 'uint256[]', internalType: 'uint256[]' },
          { name: 'mintFeeBps', type: 'uint16[]', internalType: 'uint16[]' },
          { name: 'burnFeeBps', type: 'uint16[]', internalType: 'uint16[]' },
          { name: 'flashFeeBps', type: 'uint16', internalType: 'uint16' },
        ],
      },
    ],
    outputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'token', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'units', type: 'uint256', internalType: 'uint256' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'maxInputAmounts', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [{ name: 'minted', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'units', type: 'uint256', internalType: 'uint256' },
      { name: 'to', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assetsOut', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mintFromPosition',
    inputs: [
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'units', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'minted', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burnFromPosition',
    inputs: [
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'units', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'assetsOut', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getIndex',
    inputs: [{ name: 'indexId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: 'index_',
        type: 'tuple',
        internalType: 'struct EqualIndexBaseV3.IndexView',
        components: [
          { name: 'assets', type: 'address[]', internalType: 'address[]' },
          { name: 'bundleAmounts', type: 'uint256[]', internalType: 'uint256[]' },
          { name: 'mintFeeBps', type: 'uint16[]', internalType: 'uint16[]' },
          { name: 'burnFeeBps', type: 'uint16[]', internalType: 'uint16[]' },
          { name: 'flashFeeBps', type: 'uint16', internalType: 'uint16' },
          { name: 'totalUnits', type: 'uint256', internalType: 'uint256' },
          { name: 'token', type: 'address', internalType: 'address' },
          { name: 'paused', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVaultBalance',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFeePot',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOutstandingPrincipal',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'economicBalance',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'configureLending',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'ltvBps', type: 'uint16', internalType: 'uint16' },
      { name: 'originationFeeBps', type: 'uint16', internalType: 'uint16' },
      { name: 'minDuration', type: 'uint40', internalType: 'uint40' },
      { name: 'maxDuration', type: 'uint40', internalType: 'uint40' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'borrowFromPosition',
    inputs: [
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'collateralUnits', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'duration', type: 'uint40', internalType: 'uint40' },
    ],
    outputs: [{ name: 'loanId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repayFromPosition',
    inputs: [
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'loanId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'extendFromPosition',
    inputs: [
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'loanId', type: 'uint256', internalType: 'uint256' },
      { name: 'addedDuration', type: 'uint40', internalType: 'uint40' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'recoverExpired',
    inputs: [{ name: 'loanId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getLoan',
    inputs: [{ name: 'loanId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct LibEqualIndexLending.IndexLoan',
        components: [
          { name: 'positionKey', type: 'bytes32', internalType: 'bytes32' },
          { name: 'indexId', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowAsset', type: 'address', internalType: 'address' },
          { name: 'collateralUnits', type: 'uint256', internalType: 'uint256' },
          { name: 'principal', type: 'uint256', internalType: 'uint256' },
          { name: 'maturity', type: 'uint40', internalType: 'uint40' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLockedCollateralUnits',
    inputs: [{ name: 'indexId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLendingConfig',
    inputs: [{ name: 'indexId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct LibEqualIndexLending.LendingConfig',
        components: [
          { name: 'ltvBps', type: 'uint16', internalType: 'uint16' },
          { name: 'originationFeeBps', type: 'uint16', internalType: 'uint16' },
          { name: 'minDuration', type: 'uint40', internalType: 'uint40' },
          { name: 'maxDuration', type: 'uint40', internalType: 'uint40' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxBorrowable',
    inputs: [
      { name: 'indexId', type: 'uint256', internalType: 'uint256' },
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'collateralUnits', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lendingModuleId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
]
