export const perpsExecutionFacetAbi = [
  {
    inputs: [
      { internalType: 'uint256', name: 'positionId', type: 'uint256' },
      { internalType: 'uint256', name: 'subaccountNonce', type: 'uint256' },
    ],
    name: 'createAccount',
    outputs: [{ internalType: 'bytes32', name: 'accountId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'address', name: 'collateralAsset', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        internalType: 'struct PerpsExecutionFacet.AddCollateralParams',
        name: 'p',
        type: 'tuple',
      },
    ],
    name: 'addCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'address', name: 'collateralAsset', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        internalType: 'struct PerpsExecutionFacet.RemoveCollateralParams',
        name: 'p',
        type: 'tuple',
      },
    ],
    name: 'removeCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'bool', name: 'isLong', type: 'bool' },
          { internalType: 'uint256', name: 'sizeDeltaUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'executionPriceX18', type: 'uint256' },
          { internalType: 'uint256', name: 'limitPriceX18', type: 'uint256' },
          { internalType: 'uint256', name: 'maxSlippageBps', type: 'uint256' },
          { internalType: 'uint256', name: 'feePoolId', type: 'uint256' },
          { internalType: 'uint256', name: 'executorFee', type: 'uint256' },
        ],
        internalType: 'struct PerpsExecutionFacet.OpenIncreaseParams',
        name: 'p',
        type: 'tuple',
      },
    ],
    name: 'openOrIncrease',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'int256', name: 'collateralInOut', type: 'int256' },
          { internalType: 'int256', name: 'realizedPnl', type: 'int256' },
          { internalType: 'int256', name: 'fundingPaid', type: 'int256' },
          { internalType: 'uint256', name: 'takerFee', type: 'uint256' },
          { internalType: 'uint256', name: 'lpFee', type: 'uint256' },
          { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
          { internalType: 'uint256', name: 'executorFee', type: 'uint256' },
          { internalType: 'uint256', name: 'liquidationProtocolFee', type: 'uint256' },
          { internalType: 'uint256', name: 'liquidatorReward', type: 'uint256' },
          { internalType: 'uint256', name: 'insuranceUsed', type: 'uint256' },
          { internalType: 'uint256', name: 'badDebtDelta', type: 'uint256' },
        ],
        internalType: 'struct LibPerpsStorage.SettlementDelta',
        name: 'delta',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'bool', name: 'isLong', type: 'bool' },
          { internalType: 'uint256', name: 'sizeDeltaUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'executionPriceX18', type: 'uint256' },
          { internalType: 'uint256', name: 'limitPriceX18', type: 'uint256' },
          { internalType: 'uint256', name: 'maxSlippageBps', type: 'uint256' },
          { internalType: 'uint256', name: 'feePoolId', type: 'uint256' },
          { internalType: 'uint256', name: 'executorFee', type: 'uint256' },
        ],
        internalType: 'struct PerpsExecutionFacet.DecreaseCloseParams',
        name: 'p',
        type: 'tuple',
      },
    ],
    name: 'decreaseOrClose',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'int256', name: 'collateralInOut', type: 'int256' },
          { internalType: 'int256', name: 'realizedPnl', type: 'int256' },
          { internalType: 'int256', name: 'fundingPaid', type: 'int256' },
          { internalType: 'uint256', name: 'takerFee', type: 'uint256' },
          { internalType: 'uint256', name: 'lpFee', type: 'uint256' },
          { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
          { internalType: 'uint256', name: 'executorFee', type: 'uint256' },
          { internalType: 'uint256', name: 'liquidationProtocolFee', type: 'uint256' },
          { internalType: 'uint256', name: 'liquidatorReward', type: 'uint256' },
          { internalType: 'uint256', name: 'insuranceUsed', type: 'uint256' },
          { internalType: 'uint256', name: 'badDebtDelta', type: 'uint256' },
        ],
        internalType: 'struct LibPerpsStorage.SettlementDelta',
        name: 'delta',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'positionId', type: 'uint256' },
      { internalType: 'uint256', name: 'subaccountNonce', type: 'uint256' },
    ],
    name: 'deriveAccountIdForPosition',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'accountId', type: 'bytes32' }],
    name: 'accountExists',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'accountId', type: 'bytes32' }],
    name: 'getAccount',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'positionKey', type: 'bytes32' },
          { internalType: 'uint256', name: 'positionTokenId', type: 'uint256' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsAccount',
        name: 'account',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
    ],
    name: 'getAccountCollateral',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
      { internalType: 'bool', name: 'isLong', type: 'bool' },
    ],
    name: 'getPosition',
    outputs: [
      {
        components: [
          { internalType: 'bool', name: 'isLong', type: 'bool' },
          { internalType: 'uint256', name: 'sizeUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'entryPriceX18', type: 'uint256' },
          { internalType: 'int256', name: 'entryFundingX18', type: 'int256' },
          { internalType: 'int256', name: 'realizedPnlX18', type: 'int256' },
          { internalType: 'uint64', name: 'lastIncreaseTs', type: 'uint64' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsPosition',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export const perpsViewFacetAbi = [
  {
    inputs: [{ internalType: 'bytes32', name: 'marketId', type: 'bytes32' }],
    name: 'getMarket',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
          { internalType: 'uint256', name: 'collateralPoolId', type: 'uint256' },
          { internalType: 'address', name: 'collateralAsset', type: 'address' },
          { internalType: 'address', name: 'indexAsset', type: 'address' },
          { internalType: 'bool', name: 'longEnabled', type: 'bool' },
          { internalType: 'bool', name: 'shortEnabled', type: 'bool' },
          { internalType: 'address', name: 'oracleAdapter', type: 'address' },
          { internalType: 'uint32', name: 'maxStaleness', type: 'uint32' },
          { internalType: 'uint32', name: 'maxDeviationBps', type: 'uint32' },
          { internalType: 'uint32', name: 'maxLeverageBps', type: 'uint32' },
          { internalType: 'uint32', name: 'initialMarginBps', type: 'uint32' },
          { internalType: 'uint32', name: 'maintenanceMarginBps', type: 'uint32' },
          { internalType: 'uint32', name: 'liquidationIncentiveBpsMax', type: 'uint32' },
          { internalType: 'uint256', name: 'maxOpenInterest', type: 'uint256' },
          { internalType: 'uint256', name: 'maxLongOpenInterest', type: 'uint256' },
          { internalType: 'uint256', name: 'maxShortOpenInterest', type: 'uint256' },
          { internalType: 'uint256', name: 'maxSkewAbs', type: 'uint256' },
          { internalType: 'uint32', name: 'takerFeeBps', type: 'uint32' },
          { internalType: 'uint32', name: 'makerFeeBps', type: 'uint32' },
          { internalType: 'uint32', name: 'maxFundingVelocityBpsPerDay', type: 'uint32' },
          { internalType: 'bool', name: 'pauseIncrease', type: 'bool' },
          { internalType: 'bool', name: 'pauseDecrease', type: 'bool' },
          { internalType: 'bool', name: 'pauseLiquidation', type: 'bool' },
          { internalType: 'bool', name: 'pauseSync', type: 'bool' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsMarket',
        name: 'market',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'marketId', type: 'bytes32' }],
    name: 'getMarketState',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'openInterestLong', type: 'uint256' },
          { internalType: 'uint256', name: 'openInterestShort', type: 'uint256' },
          { internalType: 'int256', name: 'skew', type: 'int256' },
          { internalType: 'int256', name: 'cumulativeFundingLongX18', type: 'int256' },
          { internalType: 'int256', name: 'cumulativeFundingShortX18', type: 'int256' },
          { internalType: 'uint64', name: 'lastFundingTs', type: 'uint64' },
          { internalType: 'uint256', name: 'insuranceBalance', type: 'uint256' },
          { internalType: 'uint256', name: 'insuranceTarget', type: 'uint256' },
          { internalType: 'uint256', name: 'badDebt', type: 'uint256' },
          { internalType: 'uint256', name: 'lpFeeIndexX18', type: 'uint256' },
          { internalType: 'uint256', name: 'protocolFeesAccrued', type: 'uint256' },
          { internalType: 'uint256', name: 'reservedCollateral', type: 'uint256' },
          { internalType: 'uint256', name: 'realizedPnlOut', type: 'uint256' },
          { internalType: 'uint256', name: 'realizedPnlIn', type: 'uint256' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsMarketState',
        name: 'state',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'accountId', type: 'bytes32' }],
    name: 'getPerpsAccount',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'positionKey', type: 'bytes32' },
          { internalType: 'uint256', name: 'positionTokenId', type: 'uint256' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsAccount',
        name: 'account',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
      { internalType: 'bool', name: 'isLong', type: 'bool' },
    ],
    name: 'getPerpsPosition',
    outputs: [
      {
        components: [
          { internalType: 'bool', name: 'isLong', type: 'bool' },
          { internalType: 'uint256', name: 'sizeUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'entryPriceX18', type: 'uint256' },
          { internalType: 'int256', name: 'entryFundingX18', type: 'int256' },
          { internalType: 'int256', name: 'realizedPnlX18', type: 'int256' },
          { internalType: 'uint64', name: 'lastIncreaseTs', type: 'uint64' },
        ],
        internalType: 'struct LibPerpsStorage.PerpsPosition',
        name: 'position',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
    ],
    name: 'getPerpsAccountCollateral',
    outputs: [{ internalType: 'uint256', name: 'collateral', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'marketId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'accountId', type: 'bytes32' },
    ],
    name: 'previewHealth',
    outputs: [
      {
        components: [
          { internalType: 'int256', name: 'equityUsdX18', type: 'int256' },
          { internalType: 'uint256', name: 'initialMarginRequiredUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'maintenanceMarginRequiredUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'minEquityForLeverageUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'openingMarginRequiredUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'leverageBps', type: 'uint256' },
          { internalType: 'int256', name: 'initialBufferUsdX18', type: 'int256' },
          { internalType: 'int256', name: 'maintenanceBufferUsdX18', type: 'int256' },
          { internalType: 'bool', name: 'meetsInitialMargin', type: 'bool' },
          { internalType: 'bool', name: 'meetsMaintenanceMargin', type: 'bool' },
        ],
        internalType: 'struct LibPerpsRisk.HealthResult',
        name: 'health',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'collateralValueUsdX18', type: 'uint256' },
          { internalType: 'uint256', name: 'positionNotionalUsdX18', type: 'uint256' },
          { internalType: 'int256', name: 'unrealizedPnlUsdX18', type: 'int256' },
          { internalType: 'int256', name: 'fundingAccruedUsdX18', type: 'int256' },
          { internalType: 'uint256', name: 'feesAccruedUsdX18', type: 'uint256' },
        ],
        internalType: 'struct LibPerpsRisk.HealthState',
        name: 'state',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'markPriceX18', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
